### ISSUE TITLE
Some issues

### ISSUE THREAD

**Issue by MioQuispe** [ludviglundgren/vscode-stockholm-theme#1]
Hey there, lovely theme! I encountered a few issues with it though, look at the props as well as jsx elements:
![image](https://user-images.githubusercontent.com/5080735/40890191-775b83f4-6772-11e8-9ada-b124b3355580.png)

**Comment by ludviglundgren** [comment]
Hello! Thanks!

The first release was a quite naive implementation, and i should probably redo some of the stuff.
Do you have any suggestions how to make it look better?

**Comment by jcuadrad** [comment]
@ludviglundgren I do have the question of why the JSX elements are Yellow, instead of Red like codesandobx.io, is this by design or for a reason I should understand?

Awesome theme!

**Comment by ludviglundgren** [comment]
Thanks @jcuadrad!

Well thats very weird, this is how it looks for me with the same code as above. 
![image](https://user-images.githubusercontent.com/16375387/41824489-3b77021e-7811-11e8-9a0e-b215f7013372.png)

It is not 100% like the codesandbox theme, and theres a couple of things that could be better which I will fix when theres time.

The only thing i can think of is that i have this extension for better syntax highlighting of es6/7 etc. https://github.com/dzannotti/vscode-babel/

Could you try that and see what happens? If that's it i'll have to include it in the readme 👍

**Comment by taoeer** [comment]
I had same issue!But but gone when i installed the 'vscode-babel'!
